global:
  arguments: 
    aws_default_region: eu-west-1
  metadata:   
    labels:
      general: 
        environment: dev
        purpose: eval-config0
      infrastructure:
        cloud: aws
        product: rds
        area: database
    matchSelectors:
      network_vars:
        labels:
          environment: dev
          purpose: eval-config0
          area: network
          region: eu-west-1
          cloud: aws
infrastructure:
  rds:
    stack_name: config0-publish:::aws_rds
    arguments:
      engine: MySQL
      engine_version: 5.7.44
      vpc_name: selector:::network_vars::vpc_name
      sg_id: selector:::network_vars::db_sg_id
      subnet_ids: selector:::network_vars::private_subnet_ids
    spec:
      serialization:
        to_base64:
          arguments:
            - cloud_tags_hash
    metadata:
      labels:
        - general
        - infrastructure
      matchSelectors:
        - network_vars
